### ISSUE TITLE
Assertion `!(srcMmaLayout && dstMmaLayout && !srcMmaLayout.isAmpere()) && "mma -> mma layout conversion is only supported on Ampere"' failed

### ISSUE THREAD

**Issue by kartikzheng** [LiveCodeBench/LiveCodeBench#14]
Hi, I'm running the code generation command and reporting an error.
The triton version is consistent with the warehouse version. When I tried to upgrade the version, I still reported the same error. What's going on here, please?
Commands:
`python -m lcb_runner.runner.main --model "codellama/CodeLlama-13b-Instruct-hf" --local_model_path /home/zhengyongk/model/CodeLlama-13b-Instruct-hf --dtype float16 --tensor_parallel_size 2 --scenario codegeneration`
Error:
`
Processed prompts:   0%|                                                                                          | 0/400 [00:00<?, ?it/s]python: /project/lib/Analysis/Allocation.cpp:43: std::pair<llvm::SmallVector<unsigned int>, llvm::SmallVector<unsigned int> > mlir::triton::getCvtOrder(mlir::Attribute, mlir::Attribute): Assertion `!(srcMmaLayout && dstMmaLayout && !srcMmaLayout.isAmpere()) && "mma -> mma layout conversion is only supported on Ampere"' failed.
*** SIGABRT received at time=1714379639 on cpu 2 ***
PC: @     0x7f89a00bfe87  (unknown)  raise
    @     0x7f89a0c29980  (unknown)  (unknown)
    @ 0x4173257325203a75  (unknown)  (unknown)
[2024-04-29 08:33:59,929 E 573427 573427] logging.cc:365: *** SIGABRT received at time=1714379639 on cpu 2 ***
[2024-04-29 08:33:59,930 E 573427 573427] logging.cc:365: PC: @     0x7f89a00bfe87  (unknown)  raise
[2024-04-29 08:33:59,934 E 573427 573427] logging.cc:365:     @     0x7f89a0c29980  (unknown)  (unknown)
[2024-04-29 08:33:59,939 E 573427 573427] logging.cc:365:     @ 0x4173257325203a75  (unknown)  (unknown)
Fatal Python error: Aborted`

**Comment by Naman-ntc** [comment]
Hi, it seems that prefix caching is not supported on Ampere GPUs (https://github.com/vllm-project/vllm/issues/2729). 
I have made it optional now, hope it works out!

**Comment by kartikzheng** [comment]
> Hi, it seems that prefix caching is not supported on Ampere GPUs ([vllm-project/vllm#2729](https://github.com/vllm-project/vllm/issues/2729)). I have made it optional now, hope it works out!

Effective, thank you very much.

**Comment by tricky61** [comment]
> > Hi, it seems that prefix caching is not supported on Ampere GPUs ([vllm-project/vllm#2729](https://github.com/vllm-project/vllm/issues/2729)). I have made it optional now, hope it works out!
> 
> Effective, thank you very much.

@Naman-ntc @kartikzheng 
so how to solve this problem？
