### ISSUE TITLE
Why is the temperature 0.2?

### ISSUE THREAD

**Issue by rodion-m** [LiveCodeBench/LiveCodeBench#15]
At first, thanks a lot for a great benchmark! I really like, cause it uses medium and hard tasks.

From readme:
> We use n=10 and temperature=0.2 for generation. Please check the [./lcb_runner/runner/parser.py](https://github.com/LiveCodeBench/LiveCodeBench/blob/45db82290ef929811e21d4cdb67c8db43010c1e0/lcb_runner/runner/parser.py) file for more details on the flags.

There is many info in the web that for GPT-4 (Turbo) and for Claude Opus for coding tasks temperature in range of 0-1 can works better. Why have you decided to use 0.2? Perhaps we should try values like 0, 0.1, 0.5 and 1?

**Comment by Naman-ntc** [comment]
We follow the Codex paper. Prompts and temperature will always cause few points of unavoidable variance and we do not consider them here

**Comment by rodion-m** [comment]
Thank you for the answer! What Codex paper you mean? I found this relevant paper: https://www.semanticscholar.org/paper/LLM-is-Like-a-Box-of-Chocolates%3A-the-of-ChatGPT-in-OuYang-Zhang/10a0541be17d10d922ffc68a3dae55a13d9c1ab9#paper-qa

And it says that 0 temperature could cause better results.
