### ISSUE TITLE
Add tasks list into leaderboard

### ISSUE THREAD

**Issue by rodion-m** [LiveCodeBench/LiveCodeBench#17]
It'll be great to see what exactly tasks are mentioned here:
![image](https://github.com/LiveCodeBench/LiveCodeBench/assets/36400912/c32580c9-dd2a-4f52-b94a-aa0e7ab4309c)

Btw, did I get it right, that this slider allows to filter tasks by their creation date time? It's also isn't cleat :)

**Comment by Naman-ntc** [comment]
The tasks are mentioned on the homepage and paper.
