### ISSUE TITLE
Add WizardLM-2 8x22B to the benchmark

### ISSUE THREAD

**Issue by rodion-m** [LiveCodeBench/LiveCodeBench#20]
In https://prollm.toqan.ai/leaderboard WizardLM-2 8x22B as good as GPT-4 Turbo. I think, this model costs to be listed into this great becnhmark.

**Comment by Naman-ntc** [comment]
WizardLM-2 has been, taken down and will not be supported

**Comment by rodion-m** [comment]
But it's still available to use. There are many forks. For example: https://huggingface.co/MaziyarPanahi/WizardLM-2-8x22B-GGUF

It should be a strong model for coding. I hope we will see it in the benchmark.
