### ISSUE TITLE
which llama3-70b Ins model in the livecodebench

### ISSUE THREAD

**Issue by HaoRenkk123** [LiveCodeBench/LiveCodeBench#21]
Hi, may I ask which llama3-70b Ins model in the livecodebench ranking corresponds to https://huggingface.co/meta-llama/Meta-Llama-3-70B-Instruct still https://huggingface.co/codellama/CodeLlama-7b-Instruct-hf Well, when I click on it from the list, it will redirect me to https://huggingface.co/meta-llama/Meta-Llama-3-70B-Instruct but what I see in the lm_styles.py is:
LanguageModel(
"meta-llama/Meta-Llama-3-70B-Instruct",
"LLama3-70b-Ins",
LMStyle.LLaMa3,
datetime(2023, 1, 1),
link="https://huggingface.co/codellama/CodeLlama-7b-Instruct-hf",
)

**Comment by Naman-ntc** [comment]
Thanks, we did use llama3-70b-instruct. thanks for the report
