### ISSUE TITLE
Interactive Problems in Benchmark

### ISSUE THREAD

**Issue by Luowaterbi** [LiveCodeBench/LiveCodeBench#29]
Some problems start with "This is an interactive problem (a type of problem where your program interacts with the judge program through Standard Input and Output).". I think these problems can't be judged by static input-output without intermediate interaction.
While executing the solutions to these problems, they will send different messages to the online judge and must get responses to continue executing. 
However, I find that the benchmark doesn't treat these problems specially. The correctness of these problems is also judged by static input-output.
I understand the difficulty of judging these problems offline, so I think we should remove these problems.

**Comment by Naman-ntc** [comment]
Thanks for the report! It looks like 1 problem in release_v1 and 2 problems in release_v2 suffer from this. You are correct, these are not amenable to current i/o-based autograder-style evaluation. Given the benchmark is released and already being used, I doubt 2 problems would make a considerable difference. I will not modify the already released problems to avoid confusion but will take this into account when collecting new problems for future updates! 

I will also maintain and errata for mistakes like this. Thanks again!
