### ISSUE TITLE
Trouble parsing private test cases in code-generation-lite

### ISSUE THREAD

**Issue by alat-rights** [LiveCodeBench/LiveCodeBench#33]
`livecodebench/code_generation`'s public and private test cases are both formatted as JSON lists of form `[{"input": ..., "output": ...}, ...]`

This is also true for `livecodebench/code_generation_lite`'s public test cases.

However, it is not true for `livecodebench/code_generation_lite`'s private test cases, which seem to be strings like `eJxrYJmaz8gABhEZQEZ0tVJmXkFpiZKVgpJhTF5iUnJMnpKOglJ+aQlUNNI1GCJUklpcUlJZkAoSLC5JycxTqtVRQNJuDNWOILAYhCCIMdI0Ji85MQloWjKQSE5KjMlLSgSam5SciG64nz+y2WACJESMJWYY7ibFG8T5KnaKHgAcinnp`.

Is this a bug?

```python
>>> lcb_codegen = load_dataset("livecodebench/code_generation_lite", version_tag="release_v2", split="test")
>>> lcb_codegen['private_test_cases'][0]
'eJxrYJmaz8gABhEZQEZ0tVJmXkFpiZKVgpJhTF5iUnJMnpKOglJ+aQlUNNI1GCJUklpcUlJZkAoSLC5JycxTqtVRQNJuDNWOILAYhCCIMdI0Ji85MQloWjKQSE5KjMlLSgSam5SciG64nz+y2WACJESMJWYY7ibFG8T5KnaKHgAcinnp'
>>> lcb_codegen['public_test_cases'][0]
'[{"input": "6\\nabc\\nacb\\nbac\\nbca\\ncab\\ncba\\n", "output": "YES\\nYES\\nYES\\nNO\\nNO\\nYES\\n", "testtype": "stdin"}]'
```

**Comment by Naman-ntc** [comment]
The private tests have been compressed for efficiency. Please follow the code at https://github.com/LiveCodeBench/LiveCodeBench/blob/45015dd2a9fa4bf445613e2f29da505dc0ca5c03/lcb_runner/benchmarks/code_generation.py#L67

**Comment by alat-rights** [comment]
Thanks!
