### ISSUE TITLE
Potential prompt bug: cllama question template unconditionally asks for model to use stdin/stdout, even if the test is functional

### ISSUE THREAD

**Issue by alat-rights** [LiveCodeBench/LiveCodeBench#35]
https://github.com/LiveCodeBench/LiveCodeBench/blob/45015dd2a9fa4bf445613e2f29da505dc0ca5c03/lcb_runner/prompts/code_generation.py#L56

It looks like cllama's prompt always has the following appended:
`f"### ANSWER (use the provided delimiters, read the inputs from stdin and write response to stdout)\n\n"`

This seems improper, since for LeetCode-sourced questions, the model is not expected to provide inputs/outputs via stdin and stdout.

**Comment by Naman-ntc** [comment]
Thanks for the report. I will update the prompt!
