### ISSUE TITLE
Appreciation and Inquiry About Substantial Data Size in Code Generations

### ISSUE THREAD

**Issue by pldlgb** [LiveCodeBench/LiveCodeBench#4]
Hello,
      I'd like to extend my deepest appreciation for the outstanding work you've been championing. Your project stands as a testament to innovation and excellence, and it's genuinely inspiring to see the impact of your hard work. 
      On a related note, as I've delved into the particulars of your project, a specific detail has piqued my curiosity. In working with the dataset related to the 400 code generations, I observed that the total data footprint is about 9GB. Given the extensive size, I couldn't help but wonder about the factors contributing to this volume.
       Would you be able to provide some insights into what drives the considerable size of the dataset associated with these code generations? Any details that help understand the composition of the data and how it might affect its management and efficacy would be profoundly helpful.
       I am looking forward to your response, and once again, thank you for your exceptional efforts and for considering my inquiry.

Warm regards,

**Comment by pldlgb** [comment]
Thank you for your response. I look forward to the updates regarding this change. Should you need any assistance in the meantime, don't hesitate to reach out.

Best wishes.

**Comment by Naman-ntc** [comment]
We have updated the dataset and codebase to make the dataset easier to use! 
The huggingface dataset is 1.2 GB now, with pruned (but mostly sufficient) tests. Note that we decompress the tests in memory leading to 2.8GB actual dataset size. 

Hope it helps!

**Comment by jcao07** [comment]
Hello,
I need to run the benchmark tasks of five versions v1-v5 concurrently. How much memory is needed?
