### ISSUE TITLE
The correct number of test set problems

### ISSUE THREAD

**Issue by SparkJiao** [LiveCodeBench/LiveCodeBench#40]
Hi, appreciate your valuable contribution!

I'm running my own model by adding a new model with newly registered prompt template. When I'm running the evaluation, I found that there are some mismatch about the amount of test questions.

Here are my evaluation script:
```
python -m lcb_runner.runner.main --model deepseek-coder-v1.5-instruct-7b-r2c  \
  --scenario codegeneration \
  --local_model_path ../experiments/deepseek-coder-v1.5-ins.7b.r2c.sft_ps_test_case.iter2.dpo.H100.dp8.v1.0.s42/checkpoint-2400/ \
  --release_version "release_v2" --not_fast --n 1 --evaluate --stop "<|EOT|>" --max_tokens 4096 --temperature 0.0
```

When I'm running the model, I noticed that the tqdm bar shows `400` questions, but I find there should be 450 questions from `2023-09-01` to `2024-09-01`. Besides, after I run
```
python -m lcb_runner.evaluation.compute_scores --eval_all_file output/DeepSeekR2C/Scenario.codegeneration_1_0.0_eval_all.json --start_date 2023-09-01 --end_date 2024-09-01
```

I get the following outputs:
```
238
Pass@1 =  0.24369747899159663
Easy Pass@1 =  0.5529411764705883
Medium Pass@1 =  0.11224489795918367
Hard Pass@1 =  0.0
Pass@5 =  1.0
Easy Pass@5 =  1.0
Medium Pass@5 =  1.0
Hard Pass@5 =  1.0
Pass@10 =  1.0
Easy Pass@10 =  1.0
Medium Pass@10 =  1.0
Hard Pass@10 =  1.0
Pass@25 =  1.0
Easy Pass@25 =  1.0
Medium Pass@25 =  1.0
Hard Pass@25 =  1.0
Pass@50 =  1.0
Easy Pass@50 =  1.0
Medium Pass@50 =  1.0
Hard Pass@50 =  1.0
Pass@100 =  1.0
Easy Pass@100 =  1.0
Medium Pass@100 =  1.0
Hard Pass@100 =  1.0
Pass@150 =  1.0
Easy Pass@150 =  1.0
Medium Pass@150 =  1.0
Hard Pass@150 =  1.0
Pass@200 =  1.0
Easy Pass@200 =  1.0
Medium Pass@200 =  1.0
Hard Pass@200 =  1.0
Pass@1: 0.24369747899159663
Easy Pass@1: 0.5529411764705883
Medium Pass@1: 0.11224489795918367
Hard Pass@1: 0.0
```

Seems that there are only 238 rows of results. Could you explain a little bit about this? Is there any mistake from my side?

BTW,
here is my registered model following readme:
```
    LanguageModel(
        "deepseek-coder-v1.5-instruct-7b-r2c",
        "DeepSeekR2C",
        LMStyle.DeepSeekR2C,
        datetime(2023, 1, 1),
        link="https://huggingface.co/chitanda/deepseek-coder-v1.5-instruct-7b-r2c",
    )
```

Thank you for your help very much!

**Comment by Naman-ntc** [comment]
> When I'm running the model, I noticed that the tqdm bar shows 400 questions, but I find there should be 450 questions from 2023-09-01 to 2024-09-01. Besides, after I run

Hmm, we are updating LiveCodeBench in different releases (currently `release_v3`) is the newest. That should give around 600 problems in the entire set. I still do not see why you are getting 400 problems in `release_v2`, it should be 511. 

You can update release_version (potentially using `--continue_existing`) and see if it gives the expected number.

**Comment by SparkJiao** [comment]
Thank you for your quick response. It seems that when I set `--not_fast`, then the choice of release version does not make difference? 
https://github.com/LiveCodeBench/LiveCodeBench/blob/main/lcb_runner/benchmarks/code_generation.py#L131-L135

Also, may I know which setting is recommended for submission and comparison, `tem=0.2, n=10` or `tem=0.0,n=1`?

Thank you very much!

**Comment by SparkJiao** [comment]
I deleted the cached huggingface dataset file and re-download it again. I find that when I set `--not_fast`, the generated test split num is `400` , and when I remove `--not_fast`, the number is correct as `511`. So should I also remove `--not_fast` when I submit my results to the leaderboard?

**Comment by Naman-ntc** [comment]
Yes, please remove the `--not_fast` option since that is not being maintained. I (personally) prefer T=0.2 N=10 estimate of pass@1 but greedy estimate should also be good. The leaderboard results are primarily T=0.2 N=10 results.
