### ISSUE TITLE
self-repair task

### ISSUE THREAD

**Issue by sidaw** [LiveCodeBench/LiveCodeBench#5]
Is this still in progress or hidden somewhere?

**Comment by Naman-ntc** [comment]
Hi Sida, thanks for raising this! The current evaluation outputs do not provide input-output information necessary for performing the self-repair. Internally, we have been using a docker [ExecEval](https://github.com/ntunlp/ExecEval) based evaluation system which we will release very soon (1-2 days)!

**Comment by Naman-ntc** [comment]
Sorry for the delay, self-repair is supported now! Please let us know if you face any issues!
