### ISSUE TITLE
Hello, If I want to use 2024.08-2024.11 datasets to test, how can I run test script?

### ISSUE THREAD

**Issue by 13416157913** [LiveCodeBench/LiveCodeBench#52]
Hello, If I want to use 2024.08-2024.11 datasets to test, how can I run test script?

**Comment by Naman-ntc** [comment]
Currently, we run models on the entire subset and filter the evaluations. You can filter the problems at https://github.com/LiveCodeBench/LiveCodeBench/blob/f05cda286956b0a976df08afe2e2a323358d32d1/lcb_runner/benchmarks/code_generation.py#L126 based on your start and end dates
