### ISSUE TITLE
When will the data for LCB release v5 be available?

### ISSUE THREAD

**Issue by archersama** [LiveCodeBench/LiveCodeBench#59]
Thank you for your hard work. Could you let me know when the data collection for release v5 will be completed? I really appreciate it.

**Comment by Naman-ntc** [comment]
Thank you for the additional interest. We are planning to introduce additional difficulty to the problems and will hopefully release many new problems after the holidays.

**Comment by archersama** [comment]
thank you

**Comment by Naman-ntc** [comment]
Hi, we have updated the huggingface benchmark with the v5 problems!
