### ISSUE TITLE
Data generation code

### ISSUE THREAD

**Issue by w14** [LiveCodeBench/LiveCodeBench#8]
Where is the code that generates the [data table](https://huggingface.co/datasets/livecodebench/execution-v2/viewer/default/train?row=0) linked from the paper? 

The repo doesn't appear to contain the names of the headers in the data table (`numsteps`, `problem_id`, ...)

**Comment by minimario** [comment]
Which part are you interested in? The only columns that are needed to run and evaluate the scenario are "code", "input", and "output". You may also use "contest_date" to evaluate across time.

Unfortunately, we are not planning on releasing the code used to generate the specific samples.

**Comment by w14** [comment]
"we are not planning on releasing the code used to generate the specific samples" - do you mean you are not planning to release the code that generates the data to be evaluated upon, or the code that is generated by the model?

**Comment by minimario** [comment]
We are not planning to release the code that generates the dataset (evaluation set).

**Comment by Naman-ntc** [comment]
Model generated codes can be found at https://huggingface.co/spaces/livecodebench/code_generation_samples/tree/main
